[test]
levels = ["syntax", "install", "registration", "instantiation", "execution"]
publish = true

[test.workflows]
timeout = 300
cpu = ["uml_mermaid.json", "uml_plantuml.json", "uml_graphviz.json"]

[test.platforms]
linux = true
macos = true
windows = true
windows_portable = true
